CREATE SCHEMA IF NOT EXISTS `FarmaciaWEB` DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`LOGIN` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`LOCALIZACAO` (
  `id` INT NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`SISTEMA_NERVOSO` (
  `id` INT NOT NULL,
  `alcoolismo` VARCHAR(45) NULL,
  `antidepressivo` VARCHAR(45) NULL,
  `disturbios_cerebrais` VARCHAR(45) NULL,
  `alzheimer` VARCHAR(45) NULL,
  `antipsicotico` VARCHAR(45) NULL,
  `esclerose_multipla` VARCHAR(45) NULL,
  `anestesico` VARCHAR(45) NULL,
  `calmante` VARCHAR(45) NULL,
  `parkinson` VARCHAR(45) NULL,
  `ansiedade` VARCHAR(45) NULL,
  `convulsao` VARCHAR(45) NULL,
  `transtorno_bipolar` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`HIGIENE_PESSOAL` (
  `id` INT NOT NULL,
  `absorvente` VARCHAR(45) NULL,
  `preservativo` VARCHAR(45) NULL,
  `desodorante` VARCHAR(45) NULL,
  `shampoo` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`INFANTIL` (
  `alimentos` VARCHAR(45) NULL,
  `brinquedos` VARCHAR(45) NULL,
  `banho` VARCHAR(45) NULL,
  `creme_assadura` VARCHAR(45) NULL,
  `fralda` VARCHAR(45) NULL,
  `higiene_bucal` VARCHAR(45) NULL,
  `acessorios` VARCHAR(45) NULL,
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`DOR_FEBRE` (
  `id` INT NOT NULL,
  `analgesico` VARCHAR(45) NULL,
  `anti-inflamatorio` VARCHAR(45) NULL,
  `contusao` VARCHAR(45) NULL,
  `colica` VARCHAR(45) NULL,
  `enxaqueca` VARCHAR(45) NULL,
  `dor_cabeca` VARCHAR(45) NULL,
  `relaxante_muscular` VARCHAR(45) NULL,
  `antitermico` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`GRIPE_RESFRIADO` (
  `id` INT NOT NULL,
  `tosse` VARCHAR(45) NULL,
  `antigripal` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`SAUDE_MULHER` (
  `id` INT NOT NULL,
  `anticoncepcional` VARCHAR(45) NULL,
  `ginecologico` VARCHAR(45) NULL,
  `menopausa` VARCHAR(45) NULL,
  `pilula_dia_seguinte` VARCHAR(45) NULL,
  `TIPO_id` INT NOT NULL,
  PRIMARY KEY (`id`, `TIPO_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`CATEGORIA` (
  `id` INT NOT NULL,
  `SAUDE_MULHER_id` INT NOT NULL,
  `GRIPES_RESFRIADOS_id` INT NOT NULL,
  `DOR_FEBRE_id` INT NOT NULL,
  `HIGIENE_PESSOAL_id` INT NOT NULL,
  `SISTEMA_NERVOSO_id` INT NOT NULL,
  `INFANTIL_id` INT NOT NULL,
  PRIMARY KEY (`id`, `SAUDE_MULHER_id`, `GRIPES_RESFRIADOS_id`, `DOR_FEBRE_id`, `HIGIENE_PESSOAL_id`, `SISTEMA_NERVOSO_id`, `INFANTIL_id`),
  INDEX `fk_CATEGORIA_SAUDE_MULHER1_idx` (`SAUDE_MULHER_id` ASC),
  INDEX `fk_CATEGORIA_GRIPES_RESFRIADOS1_idx` (`GRIPES_RESFRIADOS_id` ASC),
  INDEX `fk_CATEGORIA_DOR_FEBRE1_idx` (`DOR_FEBRE_id` ASC),
  INDEX `fk_CATEGORIA_HIGIENE_PESSOAL1_idx` (`HIGIENE_PESSOAL_id` ASC),
  INDEX `fk_CATEGORIA_SISTEMA_NERVOSO1_idx` (`SISTEMA_NERVOSO_id` ASC),
  INDEX `fk_CATEGORIA_INFANTIL1_idx` (`INFANTIL_id` ASC),
  CONSTRAINT `fk_CATEGORIA_SAUDE_MULHER1`
    FOREIGN KEY (`SAUDE_MULHER_id`)
    REFERENCES `FarmaciaWEB`.`SAUDE_MULHER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_GRIPES_RESFRIADOS1`
    FOREIGN KEY (`GRIPES_RESFRIADOS_id`)
    REFERENCES `FarmaciaWEB`.`GRIPE_RESFRIADO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_DOR_FEBRE1`
    FOREIGN KEY (`DOR_FEBRE_id`)
    REFERENCES `FarmaciaWEB`.`DOR_FEBRE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_HIGIENE_PESSOAL1`
    FOREIGN KEY (`HIGIENE_PESSOAL_id`)
    REFERENCES `FarmaciaWEB`.`HIGIENE_PESSOAL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_SISTEMA_NERVOSO1`
    FOREIGN KEY (`SISTEMA_NERVOSO_id`)
    REFERENCES `FarmaciaWEB`.`SISTEMA_NERVOSO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORIA_INFANTIL1`
    FOREIGN KEY (`INFANTIL_id`)
    REFERENCES `FarmaciaWEB`.`INFANTIL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`MEDICAMENTO` (
  `id` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `validade` DATE NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `foto_path` VARCHAR(255) NOT NULL,
  `fabricante` VARCHAR(255) NOT NULL,
  `quantidade` INT NOT NULL,
  `CATEGORIA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `CATEGORIA_id`),
  CONSTRAINT `fk_MEDICAMENTO_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_id`)
    REFERENCES `FarmaciaWEB`.`CATEGORIA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`FARMACIA` (
  `cnpj` VARCHAR(16) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `logo_path` VARCHAR(255) NOT NULL,
  `LOCALIZACAO_id` INT NOT NULL,
  `LOGIN_id` INT NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cnpj`, `LOCALIZACAO_id`, `LOGIN_id`),
  INDEX `fk_FARMACIA_LOCALIZACAO1_idx` (`LOCALIZACAO_id` ASC),
  INDEX `fk_FARMACIA_LOGIN1_idx` (`LOGIN_id` ASC),
  CONSTRAINT `fk_FARMACIA_LOCALIZACAO1`
    FOREIGN KEY (`LOCALIZACAO_id`)
    REFERENCES `FarmaciaWEB`.`LOCALIZACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FARMACIA_LOGIN1`
    FOREIGN KEY (`LOGIN_id`)
    REFERENCES `FarmaciaWEB`.`LOGIN` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`CLIENTE` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `dataNascimento` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `LOCALIZACAO_id` INT NOT NULL,
  `LOGIN_id` INT NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `LOCALIZACAO_id`, `LOGIN_id`),
  INDEX `fk_PESSOA_FISICA_LOCALIZACAO1_idx` (`LOCALIZACAO_id` ASC),
  INDEX `fk_PESSOA_FISICA_LOGIN1_idx` (`LOGIN_id` ASC),
  CONSTRAINT `fk_PESSOA_FISICA_LOCALIZACAO1`
    FOREIGN KEY (`LOCALIZACAO_id`)
    REFERENCES `FarmaciaWEB`.`LOCALIZACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESSOA_FISICA_LOGIN1`
    FOREIGN KEY (`LOGIN_id`)
    REFERENCES `FarmaciaWEB`.`LOGIN` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`INSERE` (
  `FARMACIA_cnpj` VARCHAR(16) NOT NULL,
  `MEDICAMENTO_id` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`FARMACIA_cnpj`, `MEDICAMENTO_id`),
  INDEX `fk_FARMACIA_has_MEDICAMENTO_MEDICAMENTO1_idx` (`MEDICAMENTO_id` ASC),
  INDEX `fk_FARMACIA_has_MEDICAMENTO_FARMACIA1_idx` (`FARMACIA_cnpj` ASC),
  CONSTRAINT `fk_FARMACIA_has_MEDICAMENTO_FARMACIA1`
    FOREIGN KEY (`FARMACIA_cnpj`)
    REFERENCES `FarmaciaWEB`.`FARMACIA` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FARMACIA_has_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_id`)
    REFERENCES `FarmaciaWEB`.`MEDICAMENTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`VENDA` (
  `CLIENTE_cpf` VARCHAR(11) NOT NULL,
  `MEDICAMENTO_id` INT NOT NULL,
  `data` DATE NOT NULL,
  `tipo_pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLIENTE_cpf`, `MEDICAMENTO_id`),
  INDEX `fk_CLIENTE_has_MEDICAMENTO_MEDICAMENTO1_idx` (`MEDICAMENTO_id` ASC),
  INDEX `fk_CLIENTE_has_MEDICAMENTO_CLIENTE1_idx` (`CLIENTE_cpf` ASC),
  CONSTRAINT `fk_CLIENTE_has_MEDICAMENTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_cpf`)
    REFERENCES `FarmaciaWEB`.`CLIENTE` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_id`)
    REFERENCES `FarmaciaWEB`.`MEDICAMENTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;