CREATE SCHEMA IF NOT EXISTS `FarmaciaWEB`;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`LOGIN` (
  `id` MEDIUMTEXT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`LOCALIZACAO` (
  `id` MEDIUMTEXT NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `cidade` VARCHAR(255) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`FARMACIA` (
  `cnpj` VARCHAR(16) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `logo_path` VARCHAR(255) NOT NULL,
  `LOCALIZACAO_id` INT NOT NULL,
  `LOGIN_id` MEDIUMTEXT NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cnpj`, `LOCALIZACAO_id`, `LOGIN_id`),
  INDEX `fk_FARMACIA_LOCALIZACAO1_idx` (`LOCALIZACAO_id` ASC),
  INDEX `fk_FARMACIA_LOGIN1_idx` (`LOGIN_id` ASC),
  CONSTRAINT `fk_FARMACIA_LOCALIZACAO1`
    FOREIGN KEY (`LOCALIZACAO_id`)
    REFERENCES `FarmaciaWEB`.`LOCALIZACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FARMACIA_LOGIN1`
    FOREIGN KEY (`LOGIN_id`)
    REFERENCES `FarmaciaWEB`.`LOGIN` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`CLIENTE` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `dataNascimento` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `LOCALIZACAO_id` MEDIUMTEXT NOT NULL,
  `LOGIN_id` MEDIUMTEXT NOT NULL,
  `perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`, `LOCALIZACAO_id`, `LOGIN_id`),
  INDEX `fk_PESSOA_FISICA_LOCALIZACAO1_idx` (`LOCALIZACAO_id` ASC),
  INDEX `fk_PESSOA_FISICA_LOGIN1_idx` (`LOGIN_id` ASC),
  CONSTRAINT `fk_PESSOA_FISICA_LOCALIZACAO1`
    FOREIGN KEY (`LOCALIZACAO_id`)
    REFERENCES `FarmaciaWEB`.`LOCALIZACAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PESSOA_FISICA_LOGIN1`
    FOREIGN KEY (`LOGIN_id`)
    REFERENCES `FarmaciaWEB`.`LOGIN` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`MEDICAMENTO` (
  `id` MEDIUMTEXT NOT NULL,
  `preco` DOUBLE NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `validade` DATE NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `foto_path` VARCHAR(255) NOT NULL,
  `fabricante` VARCHAR(255) NOT NULL,
  `quantidade` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`INSERE` (
  `FARMACIA_cnpj` VARCHAR(16) NOT NULL,
  `MEDICAMENTO_id` MEDIUMTEXT NOT NULL,
  `dataInsercao` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `id` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`FARMACIA_cnpj`, `MEDICAMENTO_id`, `id`),
  INDEX `fk_FARMACIA_has_MEDICAMENTO_MEDICAMENTO1_idx` (`MEDICAMENTO_id` ASC),
  INDEX `fk_FARMACIA_has_MEDICAMENTO_FARMACIA1_idx` (`FARMACIA_cnpj` ASC),
  CONSTRAINT `fk_FARMACIA_has_MEDICAMENTO_FARMACIA1`
    FOREIGN KEY (`FARMACIA_cnpj`)
    REFERENCES `FarmaciaWEB`.`FARMACIA` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FARMACIA_has_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_id`)
    REFERENCES `FarmaciaWEB`.`MEDICAMENTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `FarmaciaWEB`.`VENDA` (
  `CLIENTE_cpf` VARCHAR(11) NOT NULL,
  `MEDICAMENTO_id` MEDIUMTEXT NOT NULL,
  `dataVenda` DATE NOT NULL,
  `tipo_pagamento` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_cpf`, `MEDICAMENTO_id`, `id`),
  INDEX `fk_CLIENTE_has_MEDICAMENTO_MEDICAMENTO1_idx` (`MEDICAMENTO_id` ASC),
  INDEX `fk_CLIENTE_has_MEDICAMENTO_CLIENTE1_idx` (`CLIENTE_cpf` ASC),
  CONSTRAINT `fk_CLIENTE_has_MEDICAMENTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_cpf`)
    REFERENCES `FarmaciaWEB`.`CLIENTE` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_id`)
    REFERENCES `FarmaciaWEB`.`MEDICAMENTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



